name: Node.js CI
on: 
  workflow_dispatch:
  push:
    branches: 
      -main
  pull_request:
    branches:
      -main
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: uses Node.js
      uses: actions/setup-node@v1
      with:
        node-version: "20.x"
    - name: install cypress
      run: npm install cypress@12.12.0
    - name: run tests
      working-directory: ./swapi
      run: npx cypress run --headless
